// MIRROR of openai/codex — codex-rs/codex-backend-openapi-models/src/models/rate_limit_window_snapshot.rs
// Acquired 2026-06-23. Blob SHA: b2a6c0c228572521b4e247d2f4f47258add71c8c
// Source of truth for the per-window fields ReadCodexUsage parses.
/*
 * codex-backend
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 */
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitWindowSnapshot {
    #[serde(rename = "used_percent")]
    pub used_percent: i32,
    #[serde(rename = "limit_window_seconds")]
    pub limit_window_seconds: i32,
    #[serde(rename = "reset_after_seconds")]
    pub reset_after_seconds: i32,
    #[serde(rename = "reset_at")]
    pub reset_at: i32,
}
